version: '3.8'

services:
  web:
    build: .
    container_name: web
    ports:
      - "8080:80"
    depends_on:
      - postgres
    entrypoint: /app/entrypoint.sh

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: jou
      POSTGRES_USER: user
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

volumes:
  database_data: