<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240105084648 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE building_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE "group_id_seq" INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE request_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE room_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE "user_id_seq" INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE building (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE "group" (id INT NOT NULL, group_manager_id INT DEFAULT NULL, parent_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6DC044C5AFF355D1 ON "group" (group_manager_id)');
        $this->addSql('CREATE INDEX IDX_6DC044C5727ACA70 ON "group" (parent_id)');
        $this->addSql('CREATE TABLE request (id INT NOT NULL, author_id INT NOT NULL, requested_room_id INT NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, approved BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_3B978F9FF675F31B ON request (author_id)');
        $this->addSql('CREATE INDEX IDX_3B978F9F96DB69D7 ON request (requested_room_id)');
        $this->addSql('CREATE TABLE request_user (request_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY(request_id, user_id))');
        $this->addSql('CREATE INDEX IDX_F234F1B3427EB8A5 ON request_user (request_id)');
        $this->addSql('CREATE INDEX IDX_F234F1B3A76ED395 ON request_user (user_id)');
        $this->addSql('CREATE TABLE room (id INT NOT NULL, room_manager_id INT DEFAULT NULL, building_id INT NOT NULL, belongs_to_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, is_private BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_729F519B4CCC447F ON room (room_manager_id)');
        $this->addSql('CREATE INDEX IDX_729F519B4D2A7E12 ON room (building_id)');
        $this->addSql('CREATE INDEX IDX_729F519B33C857F5 ON room (belongs_to_id)');
        $this->addSql('CREATE TABLE "user" (id INT NOT NULL, username VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, roles JSON NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649F85E0677 ON "user" (username)');
        $this->addSql('CREATE TABLE user_room (user_id INT NOT NULL, room_id INT NOT NULL, PRIMARY KEY(user_id, room_id))');
        $this->addSql('CREATE INDEX IDX_81E1D52A76ED395 ON user_room (user_id)');
        $this->addSql('CREATE INDEX IDX_81E1D5254177093 ON user_room (room_id)');
        $this->addSql('CREATE TABLE user_group (user_id INT NOT NULL, group_id INT NOT NULL, PRIMARY KEY(user_id, group_id))');
        $this->addSql('CREATE INDEX IDX_8F02BF9DA76ED395 ON user_group (user_id)');
        $this->addSql('CREATE INDEX IDX_8F02BF9DFE54D947 ON user_group (group_id)');
        $this->addSql('ALTER TABLE "group" ADD CONSTRAINT FK_6DC044C5AFF355D1 FOREIGN KEY (group_manager_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "group" ADD CONSTRAINT FK_6DC044C5727ACA70 FOREIGN KEY (parent_id) REFERENCES "group" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE request ADD CONSTRAINT FK_3B978F9FF675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE request ADD CONSTRAINT FK_3B978F9F96DB69D7 FOREIGN KEY (requested_room_id) REFERENCES room (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE request_user ADD CONSTRAINT FK_F234F1B3427EB8A5 FOREIGN KEY (request_id) REFERENCES request (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE request_user ADD CONSTRAINT FK_F234F1B3A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE room ADD CONSTRAINT FK_729F519B4CCC447F FOREIGN KEY (room_manager_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE room ADD CONSTRAINT FK_729F519B4D2A7E12 FOREIGN KEY (building_id) REFERENCES building (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE room ADD CONSTRAINT FK_729F519B33C857F5 FOREIGN KEY (belongs_to_id) REFERENCES "group" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_room ADD CONSTRAINT FK_81E1D52A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_room ADD CONSTRAINT FK_81E1D5254177093 FOREIGN KEY (room_id) REFERENCES room (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_group ADD CONSTRAINT FK_8F02BF9DA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_group ADD CONSTRAINT FK_8F02BF9DFE54D947 FOREIGN KEY (group_id) REFERENCES "group" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (1, \'Catarina Gianneschi\', \'admin\', \'["ROLE_ADMIN"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (2, \'Catarina Gianneschi\', \'user\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (3, \'Catarina Gianneschi\', \'Gianneschi\', \'["ROLE_ADMIN"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (4, \'Marc Yearn\', \'Yearn\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (5, \'Lisette Copins\', \'Copins\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (6, \'Cherise Bethune\', \'Bethune\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (7, \'Antonella Sinkinson\', \'Sinkinson\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (8, \'Nicoline Burtonwood\', \'Burtonwood\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (9, \'Thaxter Oxlade\', \'Oxlade\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (10, \'Andreana Davidow\', \'Davidow\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (11, \'Minne Moine\', \'Moine\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (12, \'Aile Eppson\', \'Eppson\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (13, \'Bev Dugue\', \'Dugue\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (14, \'North Waldie\', \'Waldie\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (15, \'Cyrillus Gavey\', \'Gavey\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (16, \'Marcelle Iggulden\', \'Iggulden\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (17, \'Fabien Kubu\', \'Kubu\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (18, \'Leonid Hearle\', \'Hearle\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (19, \'Neysa Pibsworth\', \'Pibsworth\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (20, \'Peder Harlick\', \'Harlick\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (21, \'Alfredo Hammerson\', \'Hammerson\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (22, \'Titus Potes\', \'Potes\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (23, \'Fernando Suggitt\', \'Suggitt\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (24, \'Pepita Bertouloume\', \'Bertouloume\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (25, \'Corrie Sturr\', \'Sturr\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (26, \'Humberto Inder\', \'Inder\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (27, \'Demetria Fero\', \'Fero\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (28, \'Vinnie Poynser\', \'Poynser\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (29, \'Maxi Yankov\', \'Yankov\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (30, \'Judas Beecroft\', \'Beecroft\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (31, \'Shelby Bricknell\', \'Bricknell\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (32, \'Ilse Barensen\', \'Barensen\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (33, \'Irina Puddefoot\', \'Puddefoot\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (34, \'Adah O\'\'Henecan\', \'O\'\'Henecan\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (35, \'Fielding Chinnock\', \'Chinnock\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (36, \'Robenia Tuberfield\', \'Tuberfield\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (37, \'Pascal Kubas\', \'Kubas\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (38, \'Reynard Truran\', \'Truran\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (39, \'Carissa Larvor\', \'Larvor\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (40, \'Ahmad Townshend\', \'Townshend\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (41, \'Ramsey Fletcher\', \'Fletcher\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (42, \'Moreen Reinbach\', \'Reinbach\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (43, \'Sherri Leavy\', \'Leavy\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (44, \'Vally Tice\', \'Tice\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (45, \'Callida Kayne\', \'Kayne\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (46, \'Aurea Balloch\', \'Balloch\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (47, \'Lois Wreford\', \'Wreford\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (48, \'Mahmud Chiswell\', \'Chiswell\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (49, \'Forster Childe\', \'Childe\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (50, \'Robinetta Ennew\', \'Ennew\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (51, \'Maggi Plunket\', \'Plunket\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('insert into "user" (id, name, username, roles, password) values (52, \'Conny Piell\', \'Piell\', \'["ROLE_USER"]\', \'$2y$13$nsftqHsws6WnMKLRECQB7.T42lMiOeTbAoxodlDZg7shcSJFIAwge\')');
        $this->addSql('SELECT setval(pg_get_serial_sequence(\'user\', \'id\'), 52)');




        $this->addSql('insert into building (id, name) values (2, \'Cyrtandra\')');
        $this->addSql('insert into building (id, name) values (3, \'Yellowseed False Pimpernel\')');
        $this->addSql('SELECT setval(pg_get_serial_sequence(\'building\', \'id\'), 3)');





        $this->addSql('insert into "group" (id, name, parent_id, group_manager_id) values (1, \'Dickinson, Haley and Simonis\', 1, 7)');
        $this->addSql('insert into "group" (id, name, parent_id, group_manager_id) values (2, \'Wunsch Inc\', 1, 11)');
        $this->addSql('insert into "group" (id, name, parent_id, group_manager_id) values (3, \'Zboncak and Sons\', 1, 48)');
        $this->addSql('insert into "group" (id, name, parent_id, group_manager_id) values (4, \'Heaney, Witting and Pacocha\', 3, 22)');
        $this->addSql('insert into "group" (id, name, parent_id, group_manager_id) values (5, \'Funk-Carter\', 2, 14)');
        $this->addSql('insert into "group" (id, name, parent_id, group_manager_id) values (6, \'Bahringer-Lubowitz\', 4, 43)');
        $this->addSql('insert into "group" (id, name, parent_id, group_manager_id) values (7, \'Veum-Schneider\', 5, 26)');
        $this->addSql('insert into "group" (id, name, parent_id, group_manager_id) values (8, \'Turner-Runolfsdottir\', 2, 1)');
        $this->addSql('insert into "group" (id, name, parent_id, group_manager_id) values (9, \'Erdman-Franecki\', 7, 38)');
        $this->addSql('insert into "group" (id, name, parent_id, group_manager_id) values (10, \'Bosco, Becker and Haag\', 9, 47)');
        $this->addSql('SELECT setval(pg_get_serial_sequence(\'group\', \'id\'), 3)');




        $this->addSql('insert into user_group (user_id, group_id) values (43, 7)');
        $this->addSql('insert into user_group (user_id, group_id) values (30, 7)');
        $this->addSql('insert into user_group (user_id, group_id) values (14, 3)');
        $this->addSql('insert into user_group (user_id, group_id) values (40, 4)');
        $this->addSql('insert into user_group (user_id, group_id) values (22, 3)');
        $this->addSql('insert into user_group (user_id, group_id) values (40, 6)');
        $this->addSql('insert into user_group (user_id, group_id) values (35, 3)');
        $this->addSql('insert into user_group (user_id, group_id) values (36, 1)');
        $this->addSql('insert into user_group (user_id, group_id) values (14, 10)');
        $this->addSql('insert into user_group (user_id, group_id) values (27, 2)');
        $this->addSql('insert into user_group (user_id, group_id) values (21, 10)');
        $this->addSql('insert into user_group (user_id, group_id) values (6, 2)');
        $this->addSql('insert into user_group (user_id, group_id) values (34, 1)');
        $this->addSql('insert into user_group (user_id, group_id) values (18, 10)');
        $this->addSql('insert into user_group (user_id, group_id) values (10, 9)');
        $this->addSql('insert into user_group (user_id, group_id) values (6, 1)');
        $this->addSql('insert into user_group (user_id, group_id) values (40, 2)');
        $this->addSql('insert into user_group (user_id, group_id) values (50, 3)');
        $this->addSql('insert into user_group (user_id, group_id) values (16, 6)');
        $this->addSql('insert into user_group (user_id, group_id) values (3, 3)');
        $this->addSql('insert into user_group (user_id, group_id) values (17, 5)');
        $this->addSql('insert into user_group (user_id, group_id) values (37, 5)');
        $this->addSql('insert into user_group (user_id, group_id) values (33, 5)');
        $this->addSql('insert into user_group (user_id, group_id) values (26, 1)');
        $this->addSql('insert into user_group (user_id, group_id) values (33, 3)');
        $this->addSql('insert into user_group (user_id, group_id) values (21, 5)');
        $this->addSql('insert into user_group (user_id, group_id) values (1, 10)');
        $this->addSql('insert into user_group (user_id, group_id) values (11, 2)');
        $this->addSql('insert into user_group (user_id, group_id) values (22, 4)');
        $this->addSql('insert into user_group (user_id, group_id) values (45, 8)');
        $this->addSql('insert into user_group (user_id, group_id) values (27, 3)');
        $this->addSql('insert into user_group (user_id, group_id) values (35, 6)');
        $this->addSql('insert into user_group (user_id, group_id) values (36, 5)');
        $this->addSql('insert into user_group (user_id, group_id) values (41, 2)');
        $this->addSql('insert into user_group (user_id, group_id) values (28, 10)');
        $this->addSql('insert into user_group (user_id, group_id) values (10, 2)');
        $this->addSql('insert into user_group (user_id, group_id) values (34, 3)');
        $this->addSql('insert into user_group (user_id, group_id) values (13, 6)');
        $this->addSql('insert into user_group (user_id, group_id) values (25, 1)');
        $this->addSql('insert into user_group (user_id, group_id) values (1, 8)');
        $this->addSql('insert into user_group (user_id, group_id) values (8, 3)');
        $this->addSql('insert into user_group (user_id, group_id) values (48, 3)');
        $this->addSql('insert into user_group (user_id, group_id) values (6, 4)');
        $this->addSql('insert into user_group (user_id, group_id) values (35, 5)');
        $this->addSql('insert into user_group (user_id, group_id) values (43, 5)');
        $this->addSql('insert into user_group (user_id, group_id) values (15, 1)');
        $this->addSql('insert into user_group (user_id, group_id) values (44, 1)');
        $this->addSql('insert into user_group (user_id, group_id) values (51, 2)');
        $this->addSql('insert into user_group (user_id, group_id) values (19, 9)');
        $this->addSql('insert into user_group (user_id, group_id) values (38, 9)');
        $this->addSql('insert into user_group (user_id, group_id) values (3, 5)');
        $this->addSql('insert into user_group (user_id, group_id) values (48, 8)');
        $this->addSql('insert into user_group (user_id, group_id) values (1, 9)');
        $this->addSql('insert into user_group (user_id, group_id) values (10, 6)');
        $this->addSql('insert into user_group (user_id, group_id) values (25, 3)');
        $this->addSql('insert into user_group (user_id, group_id) values (48, 7)');
        $this->addSql('insert into user_group (user_id, group_id) values (46, 1)');
        $this->addSql('insert into user_group (user_id, group_id) values (32, 10)');
        $this->addSql('insert into user_group (user_id, group_id) values (28, 3)');
        $this->addSql('insert into user_group (user_id, group_id) values (5, 2)');
        $this->addSql('insert into user_group (user_id, group_id) values (13, 7)');
        $this->addSql('insert into user_group (user_id, group_id) values (42, 9)');
        $this->addSql('insert into user_group (user_id, group_id) values (6, 5)');
        $this->addSql('insert into user_group (user_id, group_id) values (20, 5)');
        $this->addSql('insert into user_group (user_id, group_id) values (31, 10)');
        $this->addSql('insert into user_group (user_id, group_id) values (36, 7)');
        $this->addSql('insert into user_group (user_id, group_id) values (36, 6)');
        $this->addSql('insert into user_group (user_id, group_id) values (48, 10)');
        $this->addSql('insert into user_group (user_id, group_id) values (13, 2)');
        $this->addSql('insert into user_group (user_id, group_id) values (26, 10)');
        $this->addSql('insert into user_group (user_id, group_id) values (16, 5)');
        $this->addSql('insert into user_group (user_id, group_id) values (25, 10)');
        $this->addSql('insert into user_group (user_id, group_id) values (3, 7)');
        $this->addSql('insert into user_group (user_id, group_id) values (47, 10)');
        $this->addSql('insert into user_group (user_id, group_id) values (3, 10)');
        $this->addSql('insert into user_group (user_id, group_id) values (6, 8)');
        $this->addSql('insert into user_group (user_id, group_id) values (18, 4)');
        $this->addSql('insert into user_group (user_id, group_id) values (29, 8)');
        $this->addSql('insert into user_group (user_id, group_id) values (41, 5)');
        $this->addSql('insert into user_group (user_id, group_id) values (30, 6)');
        $this->addSql('insert into user_group (user_id, group_id) values (39, 5)');
        $this->addSql('insert into user_group (user_id, group_id) values (27, 7)');
        $this->addSql('insert into user_group (user_id, group_id) values (40, 5)');
        $this->addSql('insert into user_group (user_id, group_id) values (29, 5)');
        $this->addSql('insert into user_group (user_id, group_id) values (26, 8)');
        $this->addSql('insert into user_group (user_id, group_id) values (30, 8)');
        $this->addSql('insert into user_group (user_id, group_id) values (23, 5)');
        $this->addSql('insert into user_group (user_id, group_id) values (46, 2)');
        $this->addSql('insert into user_group (user_id, group_id) values (21, 3)');
        $this->addSql('insert into user_group (user_id, group_id) values (31, 3)');
        $this->addSql('insert into user_group (user_id, group_id) values (25, 8)');
        $this->addSql('insert into user_group (user_id, group_id) values (47, 7)');
        $this->addSql('insert into user_group (user_id, group_id) values (38, 4)');






        $this->addSql('insert into room (id, room_manager_id, building_id, belongs_to_id, name, is_private) values (1, 7, 3, 9, \'habitasse platea\', true)');
        $this->addSql('insert into room (id, room_manager_id, building_id, belongs_to_id, name, is_private) values (2, 3, 3, 6, \'scelerisque mauris\', true)');
        $this->addSql('insert into room (id, room_manager_id, building_id, belongs_to_id, name, is_private) values (3, 6, 2, 10, \'metus sapien\', false)');
        $this->addSql('insert into room (id, room_manager_id, building_id, belongs_to_id, name, is_private) values (4, 47, 2, 6, \'turpis\', true)');
        $this->addSql('insert into room (id, room_manager_id, building_id, belongs_to_id, name, is_private) values (5, 32, 3, 10, \'praesent\', true)');
        $this->addSql('insert into room (id, room_manager_id, building_id, belongs_to_id, name, is_private) values (6, 30, 2, 10, \'integer\', false)');
        $this->addSql('insert into room (id, room_manager_id, building_id, belongs_to_id, name, is_private) values (7, 12, 2, 3, \'vestibulum ante\', true)');
        $this->addSql('insert into room (id, room_manager_id, building_id, belongs_to_id, name, is_private) values (8, 18, 3, 5, \'dis parturient\', true)');
        $this->addSql('insert into room (id, room_manager_id, building_id, belongs_to_id, name, is_private) values (9, 40, 3, 9, \'ipsum\', false)');
        $this->addSql('insert into room (id, room_manager_id, building_id, belongs_to_id, name, is_private) values (10, 46, 3, 6, \'dis\', false)');
        $this->addSql('insert into room (id, room_manager_id, building_id, belongs_to_id, name, is_private) values (11, 33, 2, 2, \'lacinia\', true)');
        $this->addSql('insert into room (id, room_manager_id, building_id, belongs_to_id, name, is_private) values (12, 37, 3, 5, \'orci luctus\', true)');
        $this->addSql('insert into room (id, room_manager_id, building_id, belongs_to_id, name, is_private) values (13, 17, 3, 3, \'felis sed\', false)');
        $this->addSql('insert into room (id, room_manager_id, building_id, belongs_to_id, name, is_private) values (14, 11, 2, 7, \'tortor quis\', true)');
        $this->addSql('insert into room (id, room_manager_id, building_id, belongs_to_id, name, is_private) values (15, 33, 3, 8, \'primis\', true)');
        $this->addSql('insert into room (id, room_manager_id, building_id, belongs_to_id, name, is_private) values (16, 45, 3, 6, \'diam\', true)');
        $this->addSql('insert into room (id, room_manager_id, building_id, belongs_to_id, name, is_private) values (17, 7, 3, 5, \'lobortis\', false)');
        $this->addSql('insert into room (id, room_manager_id, building_id, belongs_to_id, name, is_private) values (18, 48, 2, 10, \'magnis dis\', true)');
        $this->addSql('insert into room (id, room_manager_id, building_id, belongs_to_id, name, is_private) values (19, 22, 3, 2, \'mauris\', false)');
        $this->addSql('SELECT setval(pg_get_serial_sequence(\'room\', \'id\'), 19)');






        $this->addSql('insert into user_room (user_id, room_id) values (42, 1)');
        $this->addSql('insert into user_room (user_id, room_id) values (21, 1)');
        $this->addSql('insert into user_room (user_id, room_id) values (29, 1)');
        $this->addSql('insert into user_room (user_id, room_id) values (30, 1)');
        $this->addSql('insert into user_room (user_id, room_id) values (38, 11)');
        $this->addSql('insert into user_room (user_id, room_id) values (18, 13)');
        $this->addSql('insert into user_room (user_id, room_id) values (47, 13)');
        $this->addSql('insert into user_room (user_id, room_id) values (39, 1)');
        $this->addSql('insert into user_room (user_id, room_id) values (21, 4)');
        $this->addSql('insert into user_room (user_id, room_id) values (20, 5)');
        $this->addSql('insert into user_room (user_id, room_id) values (4, 4)');
        $this->addSql('insert into user_room (user_id, room_id) values (26, 19)');
        $this->addSql('insert into user_room (user_id, room_id) values (30, 2)');
        $this->addSql('insert into user_room (user_id, room_id) values (14, 14)');
        $this->addSql('insert into user_room (user_id, room_id) values (28, 15)');
        $this->addSql('insert into user_room (user_id, room_id) values (37, 12)');
        $this->addSql('insert into user_room (user_id, room_id) values (9, 8)');
        $this->addSql('insert into user_room (user_id, room_id) values (26, 4)');
        $this->addSql('insert into user_room (user_id, room_id) values (42, 15)');
        $this->addSql('insert into user_room (user_id, room_id) values (35, 14)');
        $this->addSql('insert into user_room (user_id, room_id) values (23, 10)');
        $this->addSql('insert into user_room (user_id, room_id) values (13, 3)');
        $this->addSql('insert into user_room (user_id, room_id) values (42, 8)');
        $this->addSql('insert into user_room (user_id, room_id) values (15, 4)');
        $this->addSql('insert into user_room (user_id, room_id) values (23, 7)');
        $this->addSql('insert into user_room (user_id, room_id) values (14, 11)');
        $this->addSql('insert into user_room (user_id, room_id) values (13, 15)');
        $this->addSql('insert into user_room (user_id, room_id) values (15, 2)');
        $this->addSql('insert into user_room (user_id, room_id) values (22, 4)');
        $this->addSql('insert into user_room (user_id, room_id) values (51, 14)');
        $this->addSql('insert into user_room (user_id, room_id) values (16, 3)');
        $this->addSql('insert into user_room (user_id, room_id) values (48, 17)');
        $this->addSql('insert into user_room (user_id, room_id) values (22, 5)');
        $this->addSql('insert into user_room (user_id, room_id) values (10, 5)');
        $this->addSql('insert into user_room (user_id, room_id) values (49, 3)');
        $this->addSql('insert into user_room (user_id, room_id) values (45, 14)');
        $this->addSql('insert into user_room (user_id, room_id) values (16, 9)');
        $this->addSql('insert into user_room (user_id, room_id) values (46, 10)');
        $this->addSql('insert into user_room (user_id, room_id) values (31, 13)');
        $this->addSql('insert into user_room (user_id, room_id) values (21, 7)');
        $this->addSql('insert into user_room (user_id, room_id) values (24, 19)');
        $this->addSql('insert into user_room (user_id, room_id) values (33, 9)');
        $this->addSql('insert into user_room (user_id, room_id) values (30, 15)');
        $this->addSql('insert into user_room (user_id, room_id) values (36, 8)');
        $this->addSql('insert into user_room (user_id, room_id) values (23, 12)');
        $this->addSql('insert into user_room (user_id, room_id) values (38, 14)');
        $this->addSql('insert into user_room (user_id, room_id) values (4, 1)');
        $this->addSql('insert into user_room (user_id, room_id) values (26, 5)');
        $this->addSql('insert into user_room (user_id, room_id) values (46, 2)');
        $this->addSql('insert into user_room (user_id, room_id) values (25, 16)');
        $this->addSql('insert into user_room (user_id, room_id) values (20, 4)');
        $this->addSql('insert into user_room (user_id, room_id) values (51, 19)');
        $this->addSql('insert into user_room (user_id, room_id) values (20, 16)');
        $this->addSql('insert into user_room (user_id, room_id) values (36, 13)');
        $this->addSql('insert into user_room (user_id, room_id) values (6, 6)');
        $this->addSql('insert into user_room (user_id, room_id) values (8, 11)');
        $this->addSql('insert into user_room (user_id, room_id) values (29, 4)');
        $this->addSql('insert into user_room (user_id, room_id) values (11, 8)');
        $this->addSql('insert into user_room (user_id, room_id) values (33, 1)');
        $this->addSql('insert into user_room (user_id, room_id) values (24, 7)');
        $this->addSql('insert into user_room (user_id, room_id) values (41, 12)');
        $this->addSql('insert into user_room (user_id, room_id) values (7, 8)');
        $this->addSql('insert into user_room (user_id, room_id) values (3, 12)');
        $this->addSql('insert into user_room (user_id, room_id) values (6, 3)');
        $this->addSql('insert into user_room (user_id, room_id) values (6, 13)');
        $this->addSql('insert into user_room (user_id, room_id) values (4, 19)');
        $this->addSql('insert into user_room (user_id, room_id) values (16, 10)');
        $this->addSql('insert into user_room (user_id, room_id) values (25, 9)');
        $this->addSql('insert into user_room (user_id, room_id) values (33, 13)');
        $this->addSql('insert into user_room (user_id, room_id) values (46, 12)');
        $this->addSql('insert into user_room (user_id, room_id) values (19, 14)');
        $this->addSql('insert into user_room (user_id, room_id) values (27, 8)');
        $this->addSql('insert into user_room (user_id, room_id) values (44, 19)');
        $this->addSql('insert into user_room (user_id, room_id) values (39, 11)');
        $this->addSql('insert into user_room (user_id, room_id) values (23, 1)');
        $this->addSql('insert into user_room (user_id, room_id) values (37, 11)');
        $this->addSql('insert into user_room (user_id, room_id) values (33, 6)');
        $this->addSql('insert into user_room (user_id, room_id) values (23, 8)');
        $this->addSql('insert into user_room (user_id, room_id) values (29, 6)');
        $this->addSql('insert into user_room (user_id, room_id) values (20, 2)');
        $this->addSql('insert into user_room (user_id, room_id) values (46, 5)');
        $this->addSql('insert into user_room (user_id, room_id) values (44, 10)');
        $this->addSql('insert into user_room (user_id, room_id) values (27, 18)');
        $this->addSql('insert into user_room (user_id, room_id) values (3, 7)');
        $this->addSql('insert into user_room (user_id, room_id) values (11, 17)');
        $this->addSql('insert into user_room (user_id, room_id) values (16, 4)');
        $this->addSql('insert into user_room (user_id, room_id) values (13, 6)');
        $this->addSql('insert into user_room (user_id, room_id) values (33, 16)');
        $this->addSql('insert into user_room (user_id, room_id) values (17, 12)');
        $this->addSql('insert into user_room (user_id, room_id) values (48, 18)');
        $this->addSql('insert into user_room (user_id, room_id) values (27, 11)');
        $this->addSql('insert into user_room (user_id, room_id) values (37, 14)');
        $this->addSql('insert into user_room (user_id, room_id) values (5, 5)');
        $this->addSql('insert into user_room (user_id, room_id) values (7, 2)');
        $this->addSql('insert into user_room (user_id, room_id) values (20, 17)');
        $this->addSql('insert into user_room (user_id, room_id) values (31, 14)');






        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (1, 34, 10, \'2023-02-11 21:45:08\', \'2024-11-02 11:32:07\', false)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (2, 28, 15, \'2023-09-10 19:57:42\', \'2024-11-02 11:32:07\', true)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (3, 36, 1, \'2023-07-11 05:16:34\', \'2024-11-02 11:32:07\', false)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (4, 34, 12, \'2023-05-06 04:15:22\', \'2024-11-02 11:32:07\', true)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (5, 35, 17, \'2023-10-11 14:32:31\', \'2024-11-02 11:32:07\', true)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (6, 21, 12, \'2023-05-20 14:51:11\', \'2024-11-02 11:32:07\', false)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (7, 50, 2, \'2023-10-08 16:47:21\', \'2024-11-02 11:32:07\', false)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (8, 51, 13, \'2023-03-02 21:20:29\', \'2024-11-02 11:32:07\', false)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (9, 38, 12, \'2023-09-22 14:02:01\', \'2024-11-02 11:32:07\', false)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (10, 52, 6, \'2023-05-25 02:25:41\', \'2024-11-02 11:32:07\', true)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (11, 12, 17, \'2023-05-17 14:58:25\', \'2024-11-02 11:32:07\', false)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (12, 8, 3, \'2023-01-24 04:18:26\', \'2024-11-02 11:32:07\', false)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (13, 36, 18, \'2023-06-07 19:26:42\', \'2024-11-02 11:32:07\', true)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (14, 25, 18, \'2023-06-15 01:40:12\', \'2024-11-02 11:32:07\', true)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (15, 43, 18, \'2023-02-06 06:33:59\', \'2024-11-02 11:32:07\', true)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (16, 30, 19, \'2023-05-29 14:28:00\', \'2024-11-02 11:32:07\', true)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (17, 15, 6, \'2023-12-18 07:48:06\', \'2024-11-02 11:32:07\', false)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (18, 4, 2, \'2023-09-11 05:07:36\', \'2024-11-02 11:32:07\', false)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (19, 49, 19, \'2023-08-05 22:18:37\', \'2024-11-02 11:32:07\', true)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (20, 46, 13, \'2023-07-30 21:39:44\', \'2024-11-02 11:32:07\', false)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (21, 30, 9, \'2023-07-09 05:31:01\', \'2024-11-02 11:32:07\', true)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (22, 13, 11, \'2023-01-18 08:49:50\', \'2024-11-02 11:32:07\', false)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (23, 4, 16, \'2023-09-30 13:51:07\', \'2024-11-02 11:32:07\', true)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (24, 31, 9, \'2023-03-31 12:03:48\', \'2024-11-02 11:32:07\', false)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (25, 43, 11, \'2023-06-27 13:36:34\', \'2024-11-02 11:32:07\', false)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (26, 34, 9, \'2023-03-10 23:01:07\', \'2024-11-02 11:32:07\', true)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (27, 5, 2, \'2023-12-05 03:47:02\', \'2024-11-02 11:32:07\', false)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (28, 49, 1, \'2023-11-29 22:29:54\', \'2024-11-02 11:32:07\', true)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (29, 51, 12, \'2023-08-30 22:41:49\', \'2024-11-02 11:32:07\', false)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (30, 46, 15, \'2023-06-06 23:15:22\', \'2024-11-02 11:32:07\', false)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (31, 27, 7, \'2023-09-06 00:57:47\', \'2024-11-02 11:32:07\', true)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (32, 11, 19, \'2023-11-02 08:53:03\', \'2024-11-02 11:32:07\', true)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (33, 13, 12, \'2023-04-23 08:01:24\', \'2024-11-02 11:32:07\', true)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (34, 46, 18, \'2023-06-06 04:34:54\', \'2024-11-02 11:32:07\', true)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (35, 16, 8, \'2023-12-28 05:53:19\', \'2024-11-02 11:32:07\', false)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (36, 8, 17, \'2023-04-03 16:11:15\', \'2024-11-02 11:32:07\', true)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (37, 12, 12, \'2023-02-17 16:35:54\', \'2024-11-02 11:32:07\', false)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (38, 50, 17, \'2023-11-01 22:51:43\', \'2024-11-02 11:32:07\', false)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (39, 5, 10, \'2023-04-07 11:51:40\', \'2024-11-02 11:32:07\', false)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (40, 36, 18, \'2023-06-12 23:02:55\', \'2024-11-02 11:32:07\', false)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (41, 50, 3, \'2023-11-02 11:32:07\', \'2024-11-02 11:32:07\', false)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (42, 24, 3, \'2023-01-07 19:21:07\', \'2024-11-02 11:32:07\', true)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (43, 29, 18, \'2023-03-06 17:28:29\', \'2024-11-02 11:32:07\', false)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (44, 50, 11, \'2023-11-17 09:08:59\', \'2024-11-02 11:32:07\', true)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (45, 30, 19, \'2023-02-24 10:17:47\', \'2024-11-02 11:32:07\', true)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (46, 18, 1, \'2023-02-26 20:29:26\', \'2024-11-02 11:32:07\', true)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (47, 16, 4, \'2023-02-20 08:07:07\', \'2024-11-02 11:32:07\', false)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (48, 34, 5, \'2023-01-05 14:14:14\', \'2024-11-02 11:32:07\', false)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (49, 17, 4, \'2023-01-08 08:52:00\', \'2024-11-02 11:32:07\', true)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (50, 21, 9, \'2023-12-12 21:12:07\', \'2024-11-02 11:32:07\', true)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (51, 25, 15, \'2023-11-03 05:19:06\', \'2024-11-02 11:32:07\', true)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (52, 43, 13, \'2023-03-22 11:39:04\', \'2024-11-02 11:32:07\', false)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (53, 27, 6, \'2023-04-03 02:27:33\', \'2024-11-02 11:32:07\', true)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (54, 41, 2, \'2023-11-16 04:26:21\', \'2024-11-02 11:32:07\', true)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (55, 44, 13, \'2023-12-23 14:16:09\', \'2024-11-02 11:32:07\', true)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (56, 21, 7, \'2023-03-27 20:08:33\', \'2024-11-02 11:32:07\', true)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (57, 19, 15, \'2023-05-16 22:58:27\', \'2024-11-02 11:32:07\', false)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (58, 40, 12, \'2023-07-14 08:39:54\', \'2024-11-02 11:32:07\', true)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (59, 44, 18, \'2023-03-03 12:58:42\', \'2024-11-02 11:32:07\', true)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (60, 47, 3, \'2023-11-17 01:55:00\', \'2024-11-02 11:32:07\', true)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (61, 38, 19, \'2023-11-24 16:55:08\', \'2024-11-02 11:32:07\', false)');
        $this->addSql('insert into request (id, author_id, requested_room_id, date, end_date, approved) values (62, 5, 4, \'2023-03-08 22:57:57\', \'2024-11-02 11:32:07\', true)');
        $this->addSql('SELECT setval(pg_get_serial_sequence(\'request\', \'id\'), 62)');







        $this->addSql('insert into request_user (request_id, user_id) values (57, 36)');
        $this->addSql('insert into request_user (request_id, user_id) values (4, 45)');
        $this->addSql('insert into request_user (request_id, user_id) values (57, 10)');
        $this->addSql('insert into request_user (request_id, user_id) values (15, 38)');
        $this->addSql('insert into request_user (request_id, user_id) values (28, 11)');
        $this->addSql('insert into request_user (request_id, user_id) values (46, 13)');
        $this->addSql('insert into request_user (request_id, user_id) values (61, 40)');
        $this->addSql('insert into request_user (request_id, user_id) values (49, 10)');
        $this->addSql('insert into request_user (request_id, user_id) values (35, 21)');
        $this->addSql('insert into request_user (request_id, user_id) values (57, 26)');
        $this->addSql('insert into request_user (request_id, user_id) values (16, 42)');
        $this->addSql('insert into request_user (request_id, user_id) values (43, 39)');
        $this->addSql('insert into request_user (request_id, user_id) values (14, 14)');
        $this->addSql('insert into request_user (request_id, user_id) values (31, 43)');
        $this->addSql('insert into request_user (request_id, user_id) values (48, 11)');
        $this->addSql('insert into request_user (request_id, user_id) values (59, 45)');
        $this->addSql('insert into request_user (request_id, user_id) values (22, 37)');
        $this->addSql('insert into request_user (request_id, user_id) values (25, 17)');
        $this->addSql('insert into request_user (request_id, user_id) values (62, 13)');
        $this->addSql('insert into request_user (request_id, user_id) values (6, 50)');
        $this->addSql('insert into request_user (request_id, user_id) values (21, 26)');
        $this->addSql('insert into request_user (request_id, user_id) values (38, 52)');
        $this->addSql('insert into request_user (request_id, user_id) values (29, 45)');
        $this->addSql('insert into request_user (request_id, user_id) values (47, 40)');
        $this->addSql('insert into request_user (request_id, user_id) values (17, 52)');
        $this->addSql('insert into request_user (request_id, user_id) values (3, 31)');
        $this->addSql('insert into request_user (request_id, user_id) values (34, 46)');
        $this->addSql('insert into request_user (request_id, user_id) values (23, 51)');
        $this->addSql('insert into request_user (request_id, user_id) values (3, 41)');
        $this->addSql('insert into request_user (request_id, user_id) values (25, 38)');
        $this->addSql('insert into request_user (request_id, user_id) values (53, 30)');
        $this->addSql('insert into request_user (request_id, user_id) values (45, 12)');
        $this->addSql('insert into request_user (request_id, user_id) values (59, 13)');
        $this->addSql('insert into request_user (request_id, user_id) values (18, 14)');
        $this->addSql('insert into request_user (request_id, user_id) values (40, 7)');
        $this->addSql('insert into request_user (request_id, user_id) values (19, 40)');
        $this->addSql('insert into request_user (request_id, user_id) values (58, 22)');
        $this->addSql('insert into request_user (request_id, user_id) values (27, 14)');
        $this->addSql('insert into request_user (request_id, user_id) values (26, 44)');
        $this->addSql('insert into request_user (request_id, user_id) values (5, 26)');
        $this->addSql('insert into request_user (request_id, user_id) values (1, 23)');
        $this->addSql('insert into request_user (request_id, user_id) values (4, 32)');
        $this->addSql('insert into request_user (request_id, user_id) values (61, 28)');
        $this->addSql('insert into request_user (request_id, user_id) values (34, 41)');
        $this->addSql('insert into request_user (request_id, user_id) values (56, 41)');
        $this->addSql('insert into request_user (request_id, user_id) values (42, 4)');
        $this->addSql('insert into request_user (request_id, user_id) values (52, 11)');
        $this->addSql('insert into request_user (request_id, user_id) values (62, 7)');
        $this->addSql('insert into request_user (request_id, user_id) values (36, 4)');
        $this->addSql('insert into request_user (request_id, user_id) values (57, 18)');
        $this->addSql('insert into request_user (request_id, user_id) values (44, 41)');
        $this->addSql('insert into request_user (request_id, user_id) values (41, 38)');
        $this->addSql('insert into request_user (request_id, user_id) values (43, 40)');
        $this->addSql('insert into request_user (request_id, user_id) values (12, 9)');
        $this->addSql('insert into request_user (request_id, user_id) values (17, 38)');
        $this->addSql('insert into request_user (request_id, user_id) values (41, 20)');
        $this->addSql('insert into request_user (request_id, user_id) values (29, 24)');
        $this->addSql('insert into request_user (request_id, user_id) values (23, 30)');
        $this->addSql('insert into request_user (request_id, user_id) values (60, 17)');
        $this->addSql('insert into request_user (request_id, user_id) values (44, 39)');
        $this->addSql('insert into request_user (request_id, user_id) values (40, 21)');
        $this->addSql('insert into request_user (request_id, user_id) values (34, 3)');
        $this->addSql('insert into request_user (request_id, user_id) values (37, 16)');
        $this->addSql('insert into request_user (request_id, user_id) values (52, 33)');
        $this->addSql('insert into request_user (request_id, user_id) values (12, 31)');
        $this->addSql('insert into request_user (request_id, user_id) values (54, 47)');
        $this->addSql('insert into request_user (request_id, user_id) values (37, 43)');
        $this->addSql('insert into request_user (request_id, user_id) values (3, 24)');
        $this->addSql('insert into request_user (request_id, user_id) values (30, 31)');
        $this->addSql('insert into request_user (request_id, user_id) values (38, 15)');
        $this->addSql('insert into request_user (request_id, user_id) values (12, 27)');
        $this->addSql('insert into request_user (request_id, user_id) values (34, 38)');
        $this->addSql('insert into request_user (request_id, user_id) values (30, 18)');
        $this->addSql('insert into request_user (request_id, user_id) values (23, 8)');
        $this->addSql('insert into request_user (request_id, user_id) values (10, 13)');
        $this->addSql('insert into request_user (request_id, user_id) values (32, 17)');
        $this->addSql('insert into request_user (request_id, user_id) values (57, 8)');
        $this->addSql('insert into request_user (request_id, user_id) values (39, 50)');
        $this->addSql('insert into request_user (request_id, user_id) values (52, 26)');
        $this->addSql('insert into request_user (request_id, user_id) values (22, 24)');
        $this->addSql('insert into request_user (request_id, user_id) values (9, 13)');
        $this->addSql('insert into request_user (request_id, user_id) values (51, 8)');
        $this->addSql('insert into request_user (request_id, user_id) values (24, 40)');
        $this->addSql('insert into request_user (request_id, user_id) values (17, 29)');
        $this->addSql('insert into request_user (request_id, user_id) values (52, 12)');
        $this->addSql('insert into request_user (request_id, user_id) values (44, 21)');
        $this->addSql('insert into request_user (request_id, user_id) values (51, 31)');
        $this->addSql('insert into request_user (request_id, user_id) values (24, 22)');
        $this->addSql('insert into request_user (request_id, user_id) values (39, 16)');
        $this->addSql('insert into request_user (request_id, user_id) values (7, 4)');
        $this->addSql('insert into request_user (request_id, user_id) values (46, 38)');
        $this->addSql('insert into request_user (request_id, user_id) values (28, 18)');
        $this->addSql('insert into request_user (request_id, user_id) values (12, 21)');
        $this->addSql('insert into request_user (request_id, user_id) values (27, 31)');
        $this->addSql('insert into request_user (request_id, user_id) values (27, 51)');
        $this->addSql('insert into request_user (request_id, user_id) values (24, 35)');
        $this->addSql('insert into request_user (request_id, user_id) values (57, 13)');
        $this->addSql('insert into request_user (request_id, user_id) values (40, 22)');
        $this->addSql('insert into request_user (request_id, user_id) values (45, 19)');
        $this->addSql('insert into request_user (request_id, user_id) values (42, 33)');
        $this->addSql('insert into request_user (request_id, user_id) values (26, 5)');
        $this->addSql('insert into request_user (request_id, user_id) values (49, 5)');
        $this->addSql('insert into request_user (request_id, user_id) values (52, 36)');
        $this->addSql('insert into request_user (request_id, user_id) values (43, 42)');
        $this->addSql('insert into request_user (request_id, user_id) values (43, 32)');
        $this->addSql('insert into request_user (request_id, user_id) values (23, 24)');
        $this->addSql('insert into request_user (request_id, user_id) values (39, 28)');
        $this->addSql('insert into request_user (request_id, user_id) values (2, 14)');
        $this->addSql('insert into request_user (request_id, user_id) values (57, 6)');
        $this->addSql('insert into request_user (request_id, user_id) values (2, 31)');
        $this->addSql('insert into request_user (request_id, user_id) values (26, 29)');
        $this->addSql('insert into request_user (request_id, user_id) values (16, 43)');
        $this->addSql('insert into request_user (request_id, user_id) values (52, 14)');
        $this->addSql('insert into request_user (request_id, user_id) values (19, 49)');
        $this->addSql('insert into request_user (request_id, user_id) values (40, 42)');
        $this->addSql('insert into request_user (request_id, user_id) values (48, 26)');
        $this->addSql('insert into request_user (request_id, user_id) values (26, 50)');
        $this->addSql('insert into request_user (request_id, user_id) values (57, 15)');
        $this->addSql('insert into request_user (request_id, user_id) values (32, 52)');
        $this->addSql('insert into request_user (request_id, user_id) values (50, 37)');
        $this->addSql('insert into request_user (request_id, user_id) values (1, 45)');
        $this->addSql('insert into request_user (request_id, user_id) values (56, 3)');
        $this->addSql('insert into request_user (request_id, user_id) values (7, 15)');
        $this->addSql('insert into request_user (request_id, user_id) values (55, 23)');
        $this->addSql('insert into request_user (request_id, user_id) values (4, 52)');
        $this->addSql('insert into request_user (request_id, user_id) values (28, 47)');
        $this->addSql('insert into request_user (request_id, user_id) values (5, 14)');
        $this->addSql('insert into request_user (request_id, user_id) values (6, 46)');
        $this->addSql('insert into request_user (request_id, user_id) values (52, 29)');
        $this->addSql('insert into request_user (request_id, user_id) values (56, 42)');
        $this->addSql('insert into request_user (request_id, user_id) values (25, 37)');
        $this->addSql('insert into request_user (request_id, user_id) values (19, 23)');
        $this->addSql('insert into request_user (request_id, user_id) values (41, 3)');
        $this->addSql('insert into request_user (request_id, user_id) values (38, 11)');
        $this->addSql('insert into request_user (request_id, user_id) values (24, 11)');
        $this->addSql('insert into request_user (request_id, user_id) values (33, 35)');
        $this->addSql('insert into request_user (request_id, user_id) values (45, 35)');
        $this->addSql('insert into request_user (request_id, user_id) values (11, 52)');
        $this->addSql('insert into request_user (request_id, user_id) values (12, 6)');
        $this->addSql('insert into request_user (request_id, user_id) values (52, 40)');
        $this->addSql('insert into request_user (request_id, user_id) values (26, 33)');
        $this->addSql('insert into request_user (request_id, user_id) values (51, 32)');
        $this->addSql('insert into request_user (request_id, user_id) values (50, 35)');
        $this->addSql('insert into request_user (request_id, user_id) values (55, 32)');
        $this->addSql('insert into request_user (request_id, user_id) values (43, 45)');
        $this->addSql('insert into request_user (request_id, user_id) values (45, 25)');
        $this->addSql('insert into request_user (request_id, user_id) values (32, 18)');
        $this->addSql('insert into request_user (request_id, user_id) values (60, 30)');
        $this->addSql('insert into request_user (request_id, user_id) values (36, 45)');
        $this->addSql('insert into request_user (request_id, user_id) values (44, 43)');
        $this->addSql('insert into request_user (request_id, user_id) values (22, 3)');
        $this->addSql('insert into request_user (request_id, user_id) values (44, 5)');
        $this->addSql('insert into request_user (request_id, user_id) values (17, 25)');
        $this->addSql('insert into request_user (request_id, user_id) values (60, 32)');
        $this->addSql('insert into request_user (request_id, user_id) values (36, 19)');
        $this->addSql('insert into request_user (request_id, user_id) values (45, 52)');
        $this->addSql('insert into request_user (request_id, user_id) values (36, 31)');
        $this->addSql('insert into request_user (request_id, user_id) values (39, 12)');
        $this->addSql('insert into request_user (request_id, user_id) values (37, 52)');
        $this->addSql('insert into request_user (request_id, user_id) values (24, 45)');
        $this->addSql('insert into request_user (request_id, user_id) values (3, 10)');
        $this->addSql('insert into request_user (request_id, user_id) values (49, 52)');
        $this->addSql('insert into request_user (request_id, user_id) values (12, 36)');
        $this->addSql('insert into request_user (request_id, user_id) values (45, 28)');
        $this->addSql('insert into request_user (request_id, user_id) values (42, 13)');
        $this->addSql('insert into request_user (request_id, user_id) values (38, 51)');
        $this->addSql('insert into request_user (request_id, user_id) values (43, 24)');
        $this->addSql('insert into request_user (request_id, user_id) values (51, 42)');
        $this->addSql('insert into request_user (request_id, user_id) values (19, 25)');
        $this->addSql('insert into request_user (request_id, user_id) values (26, 11)');
        $this->addSql('insert into request_user (request_id, user_id) values (49, 43)');
        $this->addSql('insert into request_user (request_id, user_id) values (29, 5)');
        $this->addSql('insert into request_user (request_id, user_id) values (58, 45)');
        $this->addSql('insert into request_user (request_id, user_id) values (15, 9)');
        $this->addSql('insert into request_user (request_id, user_id) values (51, 27)');
        $this->addSql('insert into request_user (request_id, user_id) values (58, 46)');
        $this->addSql('insert into request_user (request_id, user_id) values (7, 3)');
        $this->addSql('insert into request_user (request_id, user_id) values (28, 14)');
        $this->addSql('insert into request_user (request_id, user_id) values (53, 32)');
        $this->addSql('insert into request_user (request_id, user_id) values (8, 17)');
        $this->addSql('insert into request_user (request_id, user_id) values (38, 27)');
        $this->addSql('insert into request_user (request_id, user_id) values (40, 46)');
        $this->addSql('insert into request_user (request_id, user_id) values (52, 42)');
        $this->addSql('insert into request_user (request_id, user_id) values (14, 12)');
        $this->addSql('insert into request_user (request_id, user_id) values (7, 44)');
        $this->addSql('insert into request_user (request_id, user_id) values (60, 47)');
        $this->addSql('insert into request_user (request_id, user_id) values (51, 23)');
        $this->addSql('insert into request_user (request_id, user_id) values (51, 26)');
        $this->addSql('insert into request_user (request_id, user_id) values (38, 7)');
        $this->addSql('insert into request_user (request_id, user_id) values (57, 19)');
        $this->addSql('insert into request_user (request_id, user_id) values (60, 39)');
        $this->addSql('insert into request_user (request_id, user_id) values (40, 8)');
        $this->addSql('insert into request_user (request_id, user_id) values (32, 37)');
        $this->addSql('insert into request_user (request_id, user_id) values (56, 47)');
        $this->addSql('insert into request_user (request_id, user_id) values (42, 39)');
        $this->addSql('insert into request_user (request_id, user_id) values (44, 27)');
        $this->addSql('insert into request_user (request_id, user_id) values (45, 9)');
        $this->addSql('insert into request_user (request_id, user_id) values (34, 21)');
        $this->addSql('insert into request_user (request_id, user_id) values (51, 37)');
        $this->addSql('insert into request_user (request_id, user_id) values (42, 47)');
        $this->addSql('insert into request_user (request_id, user_id) values (46, 24)');
        $this->addSql('insert into request_user (request_id, user_id) values (18, 9)');
        $this->addSql('insert into request_user (request_id, user_id) values (53, 7)');
        $this->addSql('insert into request_user (request_id, user_id) values (25, 3)');
        $this->addSql('insert into request_user (request_id, user_id) values (1, 44)');
        $this->addSql('insert into request_user (request_id, user_id) values (21, 41)');
        $this->addSql('insert into request_user (request_id, user_id) values (11, 42)');
        $this->addSql('insert into request_user (request_id, user_id) values (51, 11)');
        $this->addSql('insert into request_user (request_id, user_id) values (52, 46)');
        $this->addSql('insert into request_user (request_id, user_id) values (38, 10)');
        $this->addSql('insert into request_user (request_id, user_id) values (61, 38)');
        $this->addSql('insert into request_user (request_id, user_id) values (11, 43)');
        $this->addSql('insert into request_user (request_id, user_id) values (27, 30)');
        $this->addSql('insert into request_user (request_id, user_id) values (11, 22)');
        $this->addSql('insert into request_user (request_id, user_id) values (28, 23)');
        $this->addSql('insert into request_user (request_id, user_id) values (25, 23)');
        $this->addSql('insert into request_user (request_id, user_id) values (57, 5)');
        $this->addSql('insert into request_user (request_id, user_id) values (60, 34)');
        $this->addSql('insert into request_user (request_id, user_id) values (46, 49)');
        $this->addSql('insert into request_user (request_id, user_id) values (39, 52)');
        $this->addSql('insert into request_user (request_id, user_id) values (17, 8)');
        $this->addSql('insert into request_user (request_id, user_id) values (33, 7)');
        $this->addSql('insert into request_user (request_id, user_id) values (46, 15)');
        $this->addSql('insert into request_user (request_id, user_id) values (15, 39)');
        $this->addSql('insert into request_user (request_id, user_id) values (48, 52)');
        $this->addSql('insert into request_user (request_id, user_id) values (29, 51)');
        $this->addSql('insert into request_user (request_id, user_id) values (45, 47)');
        $this->addSql('insert into request_user (request_id, user_id) values (32, 49)');
        $this->addSql('insert into request_user (request_id, user_id) values (21, 16)');
        $this->addSql('insert into request_user (request_id, user_id) values (57, 37)');
        $this->addSql('insert into request_user (request_id, user_id) values (11, 45)');
        $this->addSql('insert into request_user (request_id, user_id) values (32, 34)');
        $this->addSql('insert into request_user (request_id, user_id) values (5, 34)');
        $this->addSql('insert into request_user (request_id, user_id) values (24, 8)');
        $this->addSql('insert into request_user (request_id, user_id) values (38, 5)');
        $this->addSql('insert into request_user (request_id, user_id) values (58, 21)');
        $this->addSql('insert into request_user (request_id, user_id) values (44, 16)');
        $this->addSql('insert into request_user (request_id, user_id) values (32, 51)');
        $this->addSql('insert into request_user (request_id, user_id) values (60, 26)');
        $this->addSql('insert into request_user (request_id, user_id) values (16, 37)');
        $this->addSql('insert into request_user (request_id, user_id) values (48, 5)');
        $this->addSql('insert into request_user (request_id, user_id) values (20, 3)');
        $this->addSql('insert into request_user (request_id, user_id) values (9, 36)');
        $this->addSql('insert into request_user (request_id, user_id) values (47, 15)');
        $this->addSql('insert into request_user (request_id, user_id) values (7, 51)');
        $this->addSql('insert into request_user (request_id, user_id) values (2, 3)');
        $this->addSql('insert into request_user (request_id, user_id) values (46, 17)');
        $this->addSql('insert into request_user (request_id, user_id) values (36, 41)');
        $this->addSql('insert into request_user (request_id, user_id) values (32, 47)');
        $this->addSql('insert into request_user (request_id, user_id) values (3, 8)');
        $this->addSql('insert into request_user (request_id, user_id) values (59, 8)');
        $this->addSql('insert into request_user (request_id, user_id) values (25, 49)');
        $this->addSql('insert into request_user (request_id, user_id) values (7, 47)');
        $this->addSql('insert into request_user (request_id, user_id) values (12, 47)');
        $this->addSql('insert into request_user (request_id, user_id) values (8, 8)');
        $this->addSql('insert into request_user (request_id, user_id) values (36, 39)');
        $this->addSql('insert into request_user (request_id, user_id) values (61, 32)');
        $this->addSql('insert into request_user (request_id, user_id) values (13, 7)');
        $this->addSql('insert into request_user (request_id, user_id) values (11, 21)');
        $this->addSql('insert into request_user (request_id, user_id) values (22, 36)');
        $this->addSql('insert into request_user (request_id, user_id) values (28, 5)');
        $this->addSql('insert into request_user (request_id, user_id) values (28, 8)');
        $this->addSql('insert into request_user (request_id, user_id) values (11, 36)');
        $this->addSql('insert into request_user (request_id, user_id) values (4, 21)');
        $this->addSql('insert into request_user (request_id, user_id) values (40, 4)');
        $this->addSql('insert into request_user (request_id, user_id) values (59, 20)');
        $this->addSql('insert into request_user (request_id, user_id) values (11, 35)');
        $this->addSql('insert into request_user (request_id, user_id) values (13, 44)');
        $this->addSql('insert into request_user (request_id, user_id) values (35, 8)');
        $this->addSql('insert into request_user (request_id, user_id) values (17, 35)');
        $this->addSql('insert into request_user (request_id, user_id) values (61, 46)');
        $this->addSql('insert into request_user (request_id, user_id) values (6, 43)');
        $this->addSql('insert into request_user (request_id, user_id) values (15, 26)');
        $this->addSql('insert into request_user (request_id, user_id) values (39, 24)');
        $this->addSql('insert into request_user (request_id, user_id) values (52, 19)');
        $this->addSql('insert into request_user (request_id, user_id) values (42, 7)');
        $this->addSql('insert into request_user (request_id, user_id) values (23, 25)');
        $this->addSql('insert into request_user (request_id, user_id) values (23, 41)');
        $this->addSql('insert into request_user (request_id, user_id) values (56, 22)');
        $this->addSql('insert into request_user (request_id, user_id) values (19, 24)');
        $this->addSql('insert into request_user (request_id, user_id) values (44, 11)');
        $this->addSql('insert into request_user (request_id, user_id) values (57, 50)');
        $this->addSql('insert into request_user (request_id, user_id) values (31, 52)');
        $this->addSql('insert into request_user (request_id, user_id) values (27, 17)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('DROP SEQUENCE building_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE "group_id_seq" CASCADE');
        $this->addSql('DROP SEQUENCE request_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE room_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE "user_id_seq" CASCADE');
        $this->addSql('ALTER TABLE "group" DROP CONSTRAINT FK_6DC044C5AFF355D1');
        $this->addSql('ALTER TABLE "group" DROP CONSTRAINT FK_6DC044C5727ACA70');
        $this->addSql('ALTER TABLE request DROP CONSTRAINT FK_3B978F9FF675F31B');
        $this->addSql('ALTER TABLE request DROP CONSTRAINT FK_3B978F9F96DB69D7');
        $this->addSql('ALTER TABLE request_user DROP CONSTRAINT FK_F234F1B3427EB8A5');
        $this->addSql('ALTER TABLE request_user DROP CONSTRAINT FK_F234F1B3A76ED395');
        $this->addSql('ALTER TABLE room DROP CONSTRAINT FK_729F519B4CCC447F');
        $this->addSql('ALTER TABLE room DROP CONSTRAINT FK_729F519B4D2A7E12');
        $this->addSql('ALTER TABLE room DROP CONSTRAINT FK_729F519B33C857F5');
        $this->addSql('ALTER TABLE user_room DROP CONSTRAINT FK_81E1D52A76ED395');
        $this->addSql('ALTER TABLE user_room DROP CONSTRAINT FK_81E1D5254177093');
        $this->addSql('ALTER TABLE user_group DROP CONSTRAINT FK_8F02BF9DA76ED395');
        $this->addSql('ALTER TABLE user_group DROP CONSTRAINT FK_8F02BF9DFE54D947');
        $this->addSql('DROP TABLE building');
        $this->addSql('DROP TABLE "group"');
        $this->addSql('DROP TABLE request');
        $this->addSql('DROP TABLE request_user');
        $this->addSql('DROP TABLE room');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_room');
        $this->addSql('DROP TABLE user_group');

    }
}
